In [157]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot 
import seaborn as sns

%matplotlib inline

In [163]:
df=pd.read_excel('Final_crop_data.xlsx')

In [165]:
df=df[df['sunhours']>0]

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3412 entries, 3 to 4210
Data columns (total 16 columns):
State              3412 non-null object
District           3412 non-null object
Year               3412 non-null int64
Season             3412 non-null object
Crop               3412 non-null object
Area               3412 non-null float64
Production         3412 non-null float64
Avg_Temperature    3412 non-null float64
rainfall           3412 non-null float64
Avg_windspeed      3412 non-null float64
Avg_pressure       3412 non-null float64
Avg_humidity       3412 non-null float64
Avg_uvindex        3412 non-null float64
sunhours           3412 non-null float64
Unnamed: 14        1 non-null float64
Unnamed: 15        1 non-null float64
dtypes: float64(11), int64(1), object(4)
memory usage: 453.2+ KB


In [167]:
df.drop('Unnamed: 14',axis=1,inplace=True)
df.drop('Unnamed: 15',axis=1,inplace=True)

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3412 entries, 3 to 4210
Data columns (total 14 columns):
State              3412 non-null object
District           3412 non-null object
Year               3412 non-null int64
Season             3412 non-null object
Crop               3412 non-null object
Area               3412 non-null float64
Production         3412 non-null float64
Avg_Temperature    3412 non-null float64
rainfall           3412 non-null float64
Avg_windspeed      3412 non-null float64
Avg_pressure       3412 non-null float64
Avg_humidity       3412 non-null float64
Avg_uvindex        3412 non-null float64
sunhours           3412 non-null float64
dtypes: float64(9), int64(1), object(4)
memory usage: 399.8+ KB


In [169]:
for i in range(5,len(df.columns)):
    
    if i!=6:
        
        print('{} : \n{}\n'.format(df.columns[i],np.corrcoef(df[df.columns[i]],df['Production'])))
        
print(df.head())

Area : 
[[1.         0.82640307]
 [0.82640307 1.        ]]

Avg_Temperature : 
[[1.         0.06496055]
 [0.06496055 1.        ]]

rainfall : 
[[1.        0.0139262]
 [0.0139262 1.       ]]

Avg_windspeed : 
[[ 1.         -0.00355214]
 [-0.00355214  1.        ]]

Avg_pressure : 
[[1.         0.00232154]
 [0.00232154 1.        ]]

Avg_humidity : 
[[ 1.        -0.0217978]
 [-0.0217978  1.       ]]

Avg_uvindex : 
[[ 1.         -0.00708362]
 [-0.00708362  1.        ]]

sunhours : 
[[1.         0.12485397]
 [0.12485397 1.        ]]

            State   District  Year       Season  Crop     Area  Production  \
3  Andhra Pradesh  ANANTAPUR  2010  Kharif       Rice  34973.0    102007.0   
4  Andhra Pradesh  ANANTAPUR  2010  Rabi         Rice  24828.0     69394.0   
5  Andhra Pradesh  ANANTAPUR  2011  Kharif       Rice  37720.0     94531.0   
6  Andhra Pradesh  ANANTAPUR  2011  Rabi         Rice  10948.0     25542.0   
7  Andhra Pradesh  ANANTAPUR  2012  Kharif       Rice  22056.0     58691.0 

In [170]:
Districts=df['District'].unique()

States=df['State'].unique()

Seasons=df['Season'].unique()

def season_code(n):
    
    for i in range(len(Seasons)):
        
        if n == Seasons[i]:
            
            return i
        
df['Season_code']=df['Season'].apply(season_code)


def state_code(n):
    
    for i in range(len(States)):
        
        if n == States[i]:
            
            return i

df['State_code']=df['State'].apply(state_code)
        
def district_code(n):
    
    for i in range(len(Districts)):
        
        if n == Districts[i]:
            
            return i
df['District_code']=df['District'].apply(district_code)
        
        

In [171]:
df.head(5)


State   District  Year       Season  Crop     Area  Production  \
3  Andhra Pradesh  ANANTAPUR  2010  Kharif       Rice  34973.0    102007.0   
4  Andhra Pradesh  ANANTAPUR  2010  Rabi         Rice  24828.0     69394.0   
5  Andhra Pradesh  ANANTAPUR  2011  Kharif       Rice  37720.0     94531.0   
6  Andhra Pradesh  ANANTAPUR  2011  Rabi         Rice  10948.0     25542.0   
7  Andhra Pradesh  ANANTAPUR  2012  Kharif       Rice  22056.0     58691.0   

   Avg_Temperature  rainfall  Avg_windspeed  Avg_pressure  Avg_humidity  \
3            27.50    226.38         12.625      1007.075        70.000   
4            25.50    163.01          9.880      1010.533        59.660   
5            28.00    175.21         19.350      1007.325        62.250   
6            26.33     77.34        193.310      1011.350        53.166   
7            28.00    126.28         75.000      1007.550       238.660   

   Avg_uvindex  sunhours  Season_code  State_code  District_code  
3         5.50    1046.5            0           0              0  
4         6.33     420.0            1           0              0  
5        24.33    1023.0            0           0              0  
6         6.83     422.5            1           0              0  
7        18.75    1039.5            0           0              0

In [172]:
from sklearn.preprocessing import StandardScaler

#test=StandardScaler().fit_transform([10].values.reshape(-1,1))

NormalizedData=df

def Normalization(num):
    
    NormalizedData[df.columns[i]]=StandardScaler().fit_transform(df[df.columns[i]].values.reshape(-1,1))
    

for i in range(5,14):
    
    if i!=6:
        
        Normalization(i)


In [173]:
from sklearn.linear_model import LinearRegression , LogisticRegression , Ridge


lin = LinearRegression()

print(df.columns)

Index(['State', 'District', 'Year', 'Season', 'Crop', 'Area', 'Production',
       'Avg_Temperature', 'rainfall', 'Avg_windspeed', 'Avg_pressure',
       'Avg_humidity', 'Avg_uvindex', 'sunhours', 'Season_code', 'State_code',
       'District_code'],
      dtype='object')


In [174]:
from sklearn.cross_validation import train_test_split

X = df[['Area','Avg_Temperature', 'rainfall','Avg_humidity','sunhours', 'Season_code', 'State_code','District_code']]

y = df['Production']



x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=101)

In [175]:
lin.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [176]:
lin.score(x_test,y_test)

0.7339889806082627

In [177]:
len(df['District'].unique())

474

In [103]:
from scipy import stats


print(stats.pointbiserialr(df['Production'],df['District_code']))

PointbiserialrResult(correlation=0.1239933571908138, pvalue=3.64445335760616e-13)


In [104]:
from sklearn.svm import SVR

svm=SVR(kernel='linear')

svm.fit(x_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [105]:
svm.score(x_test,y_test)

-0.16286694932528745

In [107]:

c=np.array([0.0001,0.0005,0.001,0.005,0.1,0.5,1.0,1.5,5.0,10.0,50.0],dtype='float32')

degree=np.array([1,2,3,4,5],dtype='float32')

gamma=np.array([1.0,1.5,2.0,2.5,3.0],dtype='float32')

kernel=['rbf','linear','poly']

tol=[0.0001,0.001,0.1,1.0]

acc=[]

cost_val=[]

degree_val=[]

g=[]

kern=[]
toler=[]


maxscore=0

for i in range(11):
    
    for j in range(5):
        
        for z in range(5):
            
            for k in range(3):
                
                for m in range(4):
                    
                
                    svm=SVR(C=c[i],gamma=gamma[j],kernel=kernel[k],degree=degree[z],tol=tol[m])
                    svm.fit(x_train,y_train)
                    acc.append(svm.score(x_test,y_test))
                    cost_val.append(c[i])
                    degree_val.append(degree[z])
                    toler.append(tol[m])
                    g.append(gamma[j])
                    if kernel[k]=='rbf':
                        kern.append(0)
                    elif kernel[k]=='linear':
                        kern.append(1)
                    elif kernel[k]=='poly':
                        kern.append(2)
                
                
                
                
                if maxscore<svm.score(x_test,y_test):
                    
                    maxscore=svm.score(x_test,y_test)
                    print('C={}, gamma={}, kernel={}, degree={}, tol={} '.format(c[i],gamma[j],kernel[k],degree[z],toler[m]))
                    print(svm.score(x_test,y_test))
                    
svm=SVC(C=0.10000000149011612, gamma=3.0, kernel='poly', degree=2.0, tol=1.0 )
print(svm.fit(x_train,y_train))
print(classification_report(y_test,svm.predict(x_test)))

C=9.999999747378752e-05, gamma=2.0, kernel=poly, degree=5.0, tol=1.0 
0.07593993308349567
C=9.999999747378752e-05, gamma=2.5, kernel=poly, degree=5.0, tol=1.0 
0.18301250305582817
C=9.999999747378752e-05, gamma=3.0, kernel=poly, degree=5.0, tol=1.0 
0.2803403979134478
C=0.0005000000237487257, gamma=2.5, kernel=poly, degree=5.0, tol=1.0 
0.43409245485201625
C=0.0005000000237487257, gamma=3.0, kernel=poly, degree=5.0, tol=1.0 
0.6178772336765329
C=0.0010000000474974513, gamma=3.0, kernel=poly, degree=5.0, tol=1.0 
0.676436039396568
C=0.004999999888241291, gamma=2.5, kernel=poly, degree=5.0, tol=1.0 
0.6951501205282358
C=0.10000000149011612, gamma=1.5, kernel=poly, degree=5.0, tol=1.0 
0.7054505413383788


KeyboardInterrupt: 

In [113]:
import tensorflow as tf


x_train.head()

Area  Avg_Temperature  rainfall  Avg_humidity  sunhours  \
404   0.891550        -1.551711 -0.715084      0.518914 -1.409427   
2174 -0.695239         2.133339 -0.837434     -2.430510  0.298268   
3048  0.932414         1.105777 -0.054738      0.336266  1.835095   
3378 -0.752422         1.282943 -0.833273     -2.124203  0.399919   
36    3.151667         0.810500  0.389502      0.545973  0.786050   

      Season_code  State_code  District_code  
404      1.430689   -1.502191      -1.412150  
2174     0.941658    0.067633       0.060526  
3048    -1.014468    0.628285       0.602360  
3378     0.941658    1.301067       1.130300  
36      -1.014468   -1.726452      -1.551082

In [221]:
Area = tf.feature_column.numeric_column('Area')
Avg_Temperature = tf.feature_column.numeric_column('Avg_Temperature')
rainfall = tf.feature_column.numeric_column('rainfall')
Avg_humidity = tf.feature_column.numeric_column('Avg_humidity')
sunhours = tf.feature_column.numeric_column('sunhours')
Season_code = tf.feature_column.categorical_column_with_hash_bucket('Season',hash_bucket_size=6)
State_code = tf.feature_column.categorical_column_with_hash_bucket('State',hash_bucket_size=29)
District = tf.feature_column.categorical_column_with_hash_bucket(key='District',hash_bucket_size=500)

season = tf.feature_column.indicator_column(Season_code)

state = tf.feature_column.indicator_column(State_code)

#District = tf.feature_column.indicator_column(District)

feat_cols=[Area,Avg_Temperature,rainfall,Avg_humidity,sunhours]

In [222]:
input_func = tf.estimator.inputs.pandas_input_fn(x=x_train,y=y_train,batch_size=10,num_epochs=1000,shuffle=True)

In [259]:
estimator = tf.estimator.DNNRegressor(hidden_units=[100,100,100],feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\HP\\AppData\\Local\\Temp\\tmputidcmwf', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000000D4C481F048>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [260]:
train_func=tf.estimator.inputs.pandas_input_fn(x=x_train,y=y_train,batch_size=10,num_epochs=None,shuffle=False)

In [261]:
estimator.train(input_fn=train_func,steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\HP\AppData\Local\Temp\tmputidcmwf\model.ckpt.
INFO:tensorflow:loss = 837307700000.0, step = 1
INFO:tensorflow:global_step/sec: 222.902
INFO:tensorflow:loss = 75486580000.0, step = 101 (0.461 sec)
INFO:tensorflow:global_step/sec: 256.609
INFO:tensorflow:loss = 37505610000.0, step = 201 (0.380 sec)
INFO:tensorflow:global_step/sec: 296.974
INFO:tensorflow:loss = 50176370000.0, step = 301 (0.334 sec)
INFO:tensorflow:global_step/sec: 263.425
INFO:tensorflow:loss = 13068412000.0, step = 401 (0.391 sec)
INFO:tensorflow:global_step/sec: 282.384
INFO:tensorflow:loss = 243287690000.0, step = 501 (0.349 sec)
INFO:tensorflow:global_step/sec: 300.371
INFO:tensorflow:loss = 61841560000.0, step = 601 (0.311 sec)
I

INFO:tensorflow:global_step/sec: 327.912
INFO:tensorflow:loss = 209499600000.0, step = 7701 (0.294 sec)
INFO:tensorflow:global_step/sec: 245.044
INFO:tensorflow:loss = 1379372200.0, step = 7801 (0.416 sec)
INFO:tensorflow:global_step/sec: 214.776
INFO:tensorflow:loss = 26708400000.0, step = 7901 (0.484 sec)
INFO:tensorflow:global_step/sec: 290.305
INFO:tensorflow:loss = 18281878000.0, step = 8001 (0.331 sec)
INFO:tensorflow:global_step/sec: 214.922
INFO:tensorflow:loss = 1230798300000.0, step = 8101 (0.463 sec)
INFO:tensorflow:global_step/sec: 213.704
INFO:tensorflow:loss = 11337357000.0, step = 8201 (0.471 sec)
INFO:tensorflow:global_step/sec: 337.748
INFO:tensorflow:loss = 28451000000.0, step = 8301 (0.304 sec)
INFO:tensorflow:global_step/sec: 317.073
INFO:tensorflow:loss = 23001444000.0, step = 8401 (0.308 sec)
INFO:tensorflow:global_step/sec: 277.214
INFO:tensorflow:loss = 52910645000.0, step = 8501 (0.359 sec)
INFO:tensorflow:global_step/sec: 196.674
INFO:tensorflow:loss = 2197475

In [263]:
test_input_func=tf.estimator.inputs.pandas_input_fn(x=x_test,y=y_test,batch_size=10,num_epochs=1000,shuffle=False)

results=estimator.evaluate(input_fn=test_input_func,steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-03-19-07:18:40
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\HP\AppData\Local\Temp\tmputidcmwf\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-03-19-07:19:12
INFO:tensorflow:Saving dict for global step 10000: average_loss = 8744931000.0, global_step = 10000, label/mean = 119170.58, loss = 87449310000.0, prediction/mean = 117111.7
INFO:tensorf

In [264]:
results

{'average_loss': 8744931000.0,
 'label/mean': 119170.58,
 'loss': 87449310000.0,
 'prediction/mean': 117111.7,
 'global_step': 10000}

In [265]:
predictions=[]

for pred in estimator.predict(input_fn=test_input_func):
    predictions.append(pred['predictions'])
    #print('predicted_value : {} , actual_value : {}'.format(pred['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\HP\AppData\Local\Temp\tmputidcmwf\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [266]:
predictions = list(predictions)

actual=list(y_test)

In [267]:
for i in range(1363635,1365000):
    print('{}   ,  {}'.format(predictions[i],actual[i-1363635]))

[6726.8774]   ,  7000.0
[146247.03]   ,  73896.0
[142227.02]   ,  225491.0
[260058.6]   ,  213000.0
[587728.94]   ,  474504.0
[13537.247]   ,  7000.0
[174728.4]   ,  95523.0
[129062.06]   ,  119920.0
[21665.025]   ,  6000.0
[130743.91]   ,  52000.0
[286993.03]   ,  302368.0
[166303.62]   ,  112000.0
[7892.763]   ,  23452.0
[0.09653741]   ,  512.0
[28283.146]   ,  19468.0
[2959.4548]   ,  1908.0
[68307.28]   ,  72000.0
[6262.9023]   ,  6854.0
[5391.576]   ,  5757.0
[31547.838]   ,  2.0
[138309.78]   ,  185906.0
[18559.797]   ,  4153.0
[15390.815]   ,  20628.0
[5531.3257]   ,  158.0
[24509.08]   ,  12124.0
[2259.9211]   ,  28.0
[439446.66]   ,  789997.0
[341536.]   ,  295337.0
[19262.03]   ,  677.0
[465381.72]   ,  2000.0
[153227.62]   ,  144149.0
[50543.45]   ,  75051.0
[23631.95]   ,  40962.0
[57967.465]   ,  44660.0
[75670.586]   ,  53000.0
[516732.12]   ,  336652.0
[47740.45]   ,  44273.0
[117250.375]   ,  41000.0
[12465.865]   ,  816.0
[4501.132]   ,  5905.0
[13838.351]   ,  3772.0


[49746.31]   ,  22000.0
[6150.2666]   ,  48.0
[27297.967]   ,  20254.0
[7610.622]   ,  7000.0
[13549.113]   ,  8000.0
[17476.723]   ,  6900.0
[345313.7]   ,  746239.0
[42409.74]   ,  52912.0
[14789.973]   ,  4000.0
[394.845]   ,  5093.0
[23438.467]   ,  1421.0
[62489.543]   ,  105626.0
[14847.468]   ,  91.0
[35824.453]   ,  18000.0
[224597.97]   ,  191329.0
[15420.888]   ,  360.0
[519563.28]   ,  733313.0
[96552.36]   ,  61184.0
[149285.78]   ,  43000.0
[121.82322]   ,  2000.0
[37884.74]   ,  8166.0
[12069.407]   ,  930.0
[77058.37]   ,  88109.0
[51200.66]   ,  15161.0
[26823.932]   ,  6000.0
[86401.266]   ,  57000.0
[55821.668]   ,  28902.0
[234906.75]   ,  411888.0
[75086.375]   ,  40914.0
[69356.7]   ,  119359.0
[9947.394]   ,  15144.0
[6429.081]   ,  151.0
[57988.496]   ,  62820.0
[400425.03]   ,  165000.0
[79800.766]   ,  63083.0
[60947.77]   ,  61240.0
[33587.234]   ,  4262.0
[15767.136]   ,  7242.0
[13359.972]   ,  3006.0
[308396.72]   ,  587084.0
[12389.252]   ,  1298.0
[197547

In [248]:
len(y_test)

1365