In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot 
import seaborn as sns

%matplotlib inline

In [87]:
df=pd.read_excel('Final_crop_data.xlsx')

In [90]:
df=df[df['sunhours']>0]

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3412 entries, 3 to 4210
Data columns (total 16 columns):
State              3412 non-null object
District           3412 non-null object
Year               3412 non-null int64
Season             3412 non-null object
Crop               3412 non-null object
Area               3412 non-null float64
Production         3412 non-null float64
Avg_Temperature    3412 non-null float64
rainfall           3412 non-null float64
Avg_windspeed      3412 non-null float64
Avg_pressure       3412 non-null float64
Avg_humidity       3412 non-null float64
Avg_uvindex        3412 non-null float64
sunhours           3412 non-null float64
Unnamed: 14        1 non-null float64
Unnamed: 15        1 non-null float64
dtypes: float64(11), int64(1), object(4)
memory usage: 453.2+ KB


In [92]:
df.drop('Unnamed: 14',axis=1,inplace=True)
df.drop('Unnamed: 15',axis=1,inplace=True)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3412 entries, 3 to 4210
Data columns (total 14 columns):
State              3412 non-null object
District           3412 non-null object
Year               3412 non-null int64
Season             3412 non-null object
Crop               3412 non-null object
Area               3412 non-null float64
Production         3412 non-null float64
Avg_Temperature    3412 non-null float64
rainfall           3412 non-null float64
Avg_windspeed      3412 non-null float64
Avg_pressure       3412 non-null float64
Avg_humidity       3412 non-null float64
Avg_uvindex        3412 non-null float64
sunhours           3412 non-null float64
dtypes: float64(9), int64(1), object(4)
memory usage: 399.8+ KB


In [94]:
for i in range(5,len(df.columns)):
    
    if i!=6:
        
        print('{} : \n{}\n'.format(df.columns[i],np.corrcoef(df[df.columns[i]],df['Production'])))
        
print(df.head())

Area : 
[[1.         0.82640307]
 [0.82640307 1.        ]]

Avg_Temperature : 
[[1.         0.06496055]
 [0.06496055 1.        ]]

rainfall : 
[[1.        0.0139262]
 [0.0139262 1.       ]]

Avg_windspeed : 
[[ 1.         -0.00355214]
 [-0.00355214  1.        ]]

Avg_pressure : 
[[1.         0.00232154]
 [0.00232154 1.        ]]

Avg_humidity : 
[[ 1.        -0.0217978]
 [-0.0217978  1.       ]]

Avg_uvindex : 
[[ 1.         -0.00708362]
 [-0.00708362  1.        ]]

sunhours : 
[[1.         0.12485397]
 [0.12485397 1.        ]]

            State   District  Year       Season  Crop     Area  Production  \
3  Andhra Pradesh  ANANTAPUR  2010  Kharif       Rice  34973.0    102007.0   
4  Andhra Pradesh  ANANTAPUR  2010  Rabi         Rice  24828.0     69394.0   
5  Andhra Pradesh  ANANTAPUR  2011  Kharif       Rice  37720.0     94531.0   
6  Andhra Pradesh  ANANTAPUR  2011  Rabi         Rice  10948.0     25542.0   
7  Andhra Pradesh  ANANTAPUR  2012  Kharif       Rice  22056.0     58691.0 

In [95]:
Districts=df['District'].unique()

States=df['State'].unique()

Seasons=df['Season'].unique()

def season_code(n):
    
    for i in range(len(Seasons)):
        
        if n == Seasons[i]:
            
            return i
        
df['Season_code']=df['Season'].apply(season_code)


def state_code(n):
    
    for i in range(len(States)):
        
        if n == States[i]:
            
            return i

df['State_code']=df['State'].apply(state_code)
        
def district_code(n):
    
    for i in range(len(Districts)):
        
        if n == Districts[i]:
            
            return i
df['District_code']=df['District'].apply(district_code)
        
        

In [96]:
df.head(5)


State   District  Year       Season  Crop     Area  Production  \
3  Andhra Pradesh  ANANTAPUR  2010  Kharif       Rice  34973.0    102007.0   
4  Andhra Pradesh  ANANTAPUR  2010  Rabi         Rice  24828.0     69394.0   
5  Andhra Pradesh  ANANTAPUR  2011  Kharif       Rice  37720.0     94531.0   
6  Andhra Pradesh  ANANTAPUR  2011  Rabi         Rice  10948.0     25542.0   
7  Andhra Pradesh  ANANTAPUR  2012  Kharif       Rice  22056.0     58691.0   

   Avg_Temperature  rainfall  Avg_windspeed  Avg_pressure  Avg_humidity  \
3            27.50    226.38         12.625      1007.075        70.000   
4            25.50    163.01          9.880      1010.533        59.660   
5            28.00    175.21         19.350      1007.325        62.250   
6            26.33     77.34        193.310      1011.350        53.166   
7            28.00    126.28         75.000      1007.550       238.660   

   Avg_uvindex  sunhours  Season_code  State_code  District_code  
3         5.50    1046.5            0           0              0  
4         6.33     420.0            1           0              0  
5        24.33    1023.0            0           0              0  
6         6.83     422.5            1           0              0  
7        18.75    1039.5            0           0              0

In [97]:
from sklearn.preprocessing import StandardScaler

#test=StandardScaler().fit_transform([10].values.reshape(-1,1))

NormalizedData=df

def Normalization(num):
    
    NormalizedData[df.columns[i]]=StandardScaler().fit_transform(df[df.columns[i]].values.reshape(-1,1))
    

for i in range(5,17):
    
    if i!=6:
        
        Normalization(i)


C:\Users\HP\Anaconda3\New folder\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\HP\Anaconda3\New folder\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\HP\Anaconda3\New folder\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\HP\Anaconda3\New folder\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\HP\Anaconda3\New folder\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: D

In [98]:
from sklearn.linear_model import LinearRegression , LogisticRegression , Ridge


lin = LinearRegression()

print(df.columns)

Index(['State', 'District', 'Year', 'Season', 'Crop', 'Area', 'Production',
       'Avg_Temperature', 'rainfall', 'Avg_windspeed', 'Avg_pressure',
       'Avg_humidity', 'Avg_uvindex', 'sunhours', 'Season_code', 'State_code',
       'District_code'],
      dtype='object')


In [99]:
from sklearn.cross_validation import train_test_split

X = df[['Area','Avg_Temperature', 'rainfall','Avg_humidity','sunhours', 'Season_code', 'State_code','District_code']]

y = df['Production']



x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=101)

In [100]:
lin.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [101]:
lin.score(x_test,y_test)

0.7339889806082627

In [102]:
len(df['District'].unique())

474

In [103]:
from scipy import stats


print(stats.pointbiserialr(df['Production'],df['District_code']))

PointbiserialrResult(correlation=0.1239933571908138, pvalue=3.64445335760616e-13)


In [104]:
from sklearn.svm import SVR

svm=SVR(kernel='linear')

svm.fit(x_train,y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [105]:
svm.score(x_test,y_test)

-0.16286694932528745

In [ ]:

c=np.array([0.0001,0.0005,0.001,0.005,0.1,0.5,1.0,1.5,5.0,10.0,50.0],dtype='float32')

degree=np.array([1,2,3,4,5],dtype='float32')

gamma=np.array([1.0,1.5,2.0,2.5,3.0],dtype='float32')

kernel=['rbf','linear','poly']

tol=[0.0001,0.001,0.1,1.0]

acc=[]

cost_val=[]

degree_val=[]

g=[]

kern=[]
toler=[]


maxscore=0

for i in range(11):
    
    for j in range(5):
        
        for z in range(5):
            
            for k in range(3):
                
                for m in range(4):
                    
                
                    svm=SVR(C=c[i],gamma=gamma[j],kernel=kernel[k],degree=degree[z],tol=tol[m])
                    svm.fit(x_train,y_train)
                    acc.append(svm.score(x_test,y_test))
                    cost_val.append(c[i])
                    degree_val.append(degree[z])
                    toler.append(tol[m])
                    g.append(gamma[j])
                    if kernel[k]=='rbf':
                        kern.append(0)
                    elif kernel[k]=='linear':
                        kern.append(1)
                    elif kernel[k]=='poly':
                        kern.append(2)
                
                
                
                
                if maxscore<svm.score(x_test,y_test):
                    
                    maxscore=svm.score(x_test,y_test)
                    print('C={}, gamma={}, kernel={}, degree={}, tol={} '.format(c[i],gamma[j],kernel[k],degree[z],toler[m]))
                    print(svm.score(x_test,y_test))
                    
svm=SVC(C=0.10000000149011612, gamma=3.0, kernel='poly', degree=2.0, tol=1.0 )
print(svm.fit(x_train,y_train))
print(classification_report(y_test,svm.predict(x_test)))

C=9.999999747378752e-05, gamma=2.0, kernel=poly, degree=5.0, tol=1.0 
0.07593993308349567
C=9.999999747378752e-05, gamma=2.5, kernel=poly, degree=5.0, tol=1.0 
0.18301250305582817
C=9.999999747378752e-05, gamma=3.0, kernel=poly, degree=5.0, tol=1.0 
0.2803403979134478
C=0.0005000000237487257, gamma=2.5, kernel=poly, degree=5.0, tol=1.0 
0.43409245485201625
C=0.0005000000237487257, gamma=3.0, kernel=poly, degree=5.0, tol=1.0 
0.6178772336765329
C=0.0010000000474974513, gamma=3.0, kernel=poly, degree=5.0, tol=1.0 
0.676436039396568
C=0.004999999888241291, gamma=2.5, kernel=poly, degree=5.0, tol=1.0 
0.6951501205282358
C=0.10000000149011612, gamma=1.5, kernel=poly, degree=5.0, tol=1.0 
0.7054505413383788
